CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(200) NULL,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    Phone NVARCHAR(50) NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Role INT NOT NULL DEFAULT 0
);
CREATE TABLE Reports (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Type INT NOT NULL,
   Title NVARCHAR(250) NOT NULL,
    Category NVARCHAR(200) NULL,
    Description NVARCHAR(MAX) NULL,
    Location NVARCHAR(300) NULL,
    Date DATETIME NOT NULL,
    ImagePath NVARCHAR(MAX) NULL,
    Phone NVARCHAR(100) NULL,
    ExtraInfo NVARCHAR(MAX) NULL,
    Status INT NOT NULL DEFAULT 0,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
